### ISSUE TITLE
Does this support only screen sharing. Or can the mouse be controlled remotely. 

### ISSUE THREAD

**Issue by rudrarajurahul** [anirudhganwal06/remote-me#1]
Does this support only screen sharing. Or can the mouse be controlled remotely ?

**Comment by anirudhganwal06** [comment]
Change the "-mouse" strings from both lines [here](https://github.com/anirudhganwal06/remote-me/blob/4077ea2a39df6b73f48e43e833da32e9dd6eda70/remote-me/main.py#L154#L156) to "mouse" and then you can control the movement of mouse. Clicking, scrolling etc are not yet supported

**Comment by rudrarajurahul** [comment]
Ooh okok. I have tried to setup the environment on my local system and was able to run it with no issues. So can I share my screen or watch other's screen only on the local network ?

**Comment by anirudhganwal06** [comment]
I haven't tried connecting and testing two machines on different networks.
But I think that should also work.
Sorry for a late reply.

**Comment by Rahul-Yadav-1996** [comment]
in this multiple window open (grab screen ). is there any solution of this .
pls suggest

**Comment by anirudhganwal06** [comment]
Can you please share a screenshot of the issue "grab screen". I am not able to understand what that mean.
